package model.report;

import model.user.User;
import model.user.UserHashMap;

import java.time.LocalDateTime;

/**
 *  A user can submit this report any time they are logged in. This report consists of:
 *      Date and time of report (can be autogenerated by application)
 *      Report Number (must be autogenerated by application)
 *      Name of reporter (can be autogenerated from user information)
 *      Location of water (manually entered. using any kind of location services or gps is extra credit).
 *      Type of water (Bottled, Well, Stream, Lake, Spring, Other)
 *      Condition of water (Waste, Treatable-Clear, Treatable-Muddy, Potable)
 */
public class WaterSourceReport {

    private LocalDateTime reportTime;
    private int reportNumber;
    private User reporter;
    private String location;
    private WaterType waterType;
    private WaterCondition waterCondition;

    private static int numOfReports;

    public WaterSourceReport(String location, WaterType waterType, WaterCondition waterCondition) {
        //Report time autogenerated when report is submitted
        reportTime = LocalDateTime.now();

        //Reporter is autogenerated as current user
        reporter = UserHashMap.soleInstance.getCurrentUser();

        //For now report number is just the number of reports created so far
        numOfReports++;
        reportNumber = numOfReports;

        this.location = location;
        this.waterType = waterType;
        this.waterCondition = waterCondition;
    }

    //Test to see if reports are working
    public void getOutput() {
        System.out.println("----------------------------------------");
        System.out.println(reportNumber + " @ " + location + " at " + reportTime + " by " + reporter.getName());
        System.out.println(waterType + " | " + waterCondition);
        System.out.println("----------------------------------------");
    }

    public LocalDateTime getReportTime() {
        return reportTime;
    }

    public int getReportNumber() {
        return reportNumber;
    }

    public User getReporter() {
        return reporter;
    }

    public String getLocation() {
        return location;
    }

    public WaterType getWaterType() {
        return waterType;
    }

    public WaterCondition getWaterCondition() {
        return waterCondition;
    }
}
